### PR TITLE
Added all movies list to movies page

### PR DESCRIPTION
**Pull request by mohittk**
Check the deploy to verify all movies.

### CODE REVIEW

**Comment by mohittk** [comment]
When will I get reply of this PR? @maintainers

**Comment by aum-singhal** [comment]
Really Great job done @mohittk 
but as want to give chance to maximum members, we can't accept your pull request.
thanks for understanding
😄

**Comment by mohittk** [comment]
> Really Great job done @mohittk The page looks awesome 😍 but as want to give chance to maximum members, we can't accept your pull request. thanks for understanding 😄

Bro, my work gone in vain? There are many changes that can be done even though you merge my pull request. I had made a lot efforts for it. Hope you understand. Please merge my request.

**Comment by mohittk** [comment]
> Really Great job done @mohittk The page looks awesome 😍 but as want to give chance to maximum members, we can't accept your pull request. thanks for understanding 😄
If you want to let more members contribute, just write on README that each member should made one card only. And that's serious.

**Comment by mohittk** [comment]
Any intimation on this PR? Just reply to my comment.

**Comment by mohittk** [comment]
You people are inco-operative. Try to be good maintainers.

**Pull request closed without merging**
